// Dummy data for the application

// Dummy Vendors
export const dummyVendors = [
  {
    id: "v1",
    name: "Elegant Moments Photography",
    email: "contact@elegantmoments.com",
    phone: "(555) 123-4567",
    category: "Photography",
    location: "New York, NY",
    rating: 4.9,
    reviewCount: 124,
    isPremium: true,
    premiumTier: "top10",
    premiumPosition: 1,
    bio: "Professional wedding photography with 10+ years of experience capturing beautiful moments.",
    website: "https://elegantmoments.com",
    portfolio: [
      "https://images.unsplash.com/photo-1537633552985-df8429e8048b",
      "https://images.unsplash.com/photo-1537633552985-df8429e8048b",
      "https://images.unsplash.com/photo-1537633552985-df8429e8048b",
    ],
    services: [
      { name: "Wedding Day Coverage", price: "$2,500" },
      { name: "Engagement Session", price: "$500" },
      { name: "Wedding Album", price: "$800" },
    ],
  },
  {
    id: "v2",
    name: "Dreamy Venues",
    email: "info@dreamyvenues.com",
    phone: "(555) 234-5678",
    category: "Venues",
    location: "Los Angeles, CA",
    rating: 4.8,
    reviewCount: 98,
    isPremium: true,
    premiumTier: "top10",
    premiumPosition: 2,
    bio: "Stunning wedding venues with breathtaking views and exceptional service.",
    website: "https://dreamyvenues.com",
    portfolio: [
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3",
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3",
      "https://images.unsplash.com/photo-1519167758481-83f550bb49b3",
    ],
    services: [
      { name: "Full Venue Rental", price: "$5,000" },
      { name: "Ceremony Only", price: "$2,000" },
      { name: "Reception Only", price: "$3,500" },
    ],
  },
  {
    id: "v3",
    name: "Floral Fantasies",
    email: "flowers@floralfantasies.com",
    phone: "(555) 345-6789",
    category: "Florists",
    location: "Chicago, IL",
    rating: 4.7,
    reviewCount: 86,
    isPremium: true,
    premiumTier: "top10",
    premiumPosition: 3,
    bio: "Creating stunning floral arrangements for weddings and special events.",
    website: "https://floralfantasies.com",
    portfolio: [
      "https://images.unsplash.com/photo-1464982326199-86f32f81b211",
      "https://images.unsplash.com/photo-1464982326199-86f32f81b211",
      "https://images.unsplash.com/photo-1464982326199-86f32f81b211",
    ],
    services: [
      { name: "Bridal Bouquet", price: "$250" },
      { name: "Centerpieces", price: "$75 each" },
      { name: "Full Wedding Package", price: "$2,000" },
    ],
  },
  {
    id: "v4",
    name: "Harmony Wedding DJs",
    email: "bookings@harmonydjs.com",
    phone: "(555) 456-7890",
    category: "Music",
    location: "Miami, FL",
    rating: 4.8,
    reviewCount: 112,
    isPremium: true,
    premiumTier: "top10",
    premiumPosition: 4,
    bio: "Professional DJs providing the perfect soundtrack for your special day.",
    website: "https://harmonydjs.com",
    portfolio: [
      "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec",
      "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec",
      "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec",
    ],
    services: [
      { name: "6 Hour Wedding Package", price: "$1,200" },
      { name: "Ceremony + Reception", price: "$1,500" },
      { name: "Lighting Package Add-on", price: "$500" },
    ],
  },
  {
    id: "v5",
    name: "Sweet Celebrations Bakery",
    email: "cakes@sweetcelebrations.com",
    phone: "(555) 567-8901",
    category: "Cakes",
    location: "Seattle, WA",
    rating: 4.6,
    reviewCount: 76,
    isPremium: true,
    premiumTier: "top50",
    premiumPosition: 12,
    bio: "Delicious and beautiful custom wedding cakes and desserts.",
    website: "https://sweetcelebrations.com",
    portfolio: [
      "https://images.unsplash.com/photo-1535254973040-607b474cb50d",
      "https://images.unsplash.com/photo-1535254973040-607b474cb50d",
      "https://images.unsplash.com/photo-1535254973040-607b474cb50d",
    ],
    services: [
      { name: "3-Tier Wedding Cake", price: "$600" },
      { name: "Cupcake Tower", price: "$400" },
      { name: "Dessert Bar", price: "$800" },
    ],
  },
];

// Dummy Clients
export const dummyClients = [
  {
    id: "c1",
    name: "Emily & Michael Johnson",
    email: "emily.johnson@example.com",
    phone: "(555) 123-9876",
    weddingDate: "2023-06-15",
    location: "New York, NY",
    budget: 35000,
    isPremium: true,
    bio: "Planning our dream wedding in New York City. Looking for amazing vendors to make our day special!",
  },
  {
    id: "c2",
    name: "David & Sarah Williams",
    email: "david.williams@example.com",
    phone: "(555) 234-8765",
    weddingDate: "2023-08-22",
    location: "Los Angeles, CA",
    budget: 50000,
    isPremium: true,
    bio: "Excited to plan our beach wedding in Southern California. Searching for the perfect vendors!",
  },
  {
    id: "c3",
    name: "James & Jessica Brown",
    email: "james.brown@example.com",
    phone: "(555) 345-7654",
    weddingDate: "2023-10-08",
    location: "Chicago, IL",
    budget: 30000,
    isPremium: false,
    bio: "Planning a fall wedding in Chicago. Looking for vendors who can work with our vision and budget.",
  },
  {
    id: "c4",
    name: "Robert & Jennifer Davis",
    email: "robert.davis@example.com",
    phone: "(555) 456-6543",
    weddingDate: "2023-12-30",
    location: "Denver, CO",
    budget: 40000,
    isPremium: false,
    bio: "Planning a winter wonderland wedding in Colorado. Excited to find the perfect team of vendors!",
  },
  {
    id: "c5",
    name: "Christopher & Amanda Wilson",
    email: "chris.wilson@example.com",
    phone: "(555) 567-5432",
    weddingDate: "2024-02-14",
    location: "Seattle, WA",
    budget: 25000,
    isPremium: true,
    bio: "Valentine's Day wedding in Seattle! Looking for vendors who can create a romantic atmosphere.",
  },
];

// Dummy Jobs/Postings
export const dummyJobs = [
  {
    id: "j1",
    clientId: "c1",
    title: "Wedding Photographer Needed for NYC Wedding",
    category: "Photography",
    description:
      "Looking for an experienced wedding photographer for our June wedding in Manhattan. Must have experience with indoor/outdoor venues and a photojournalistic style.",
    budget: "$2,000 - $3,000",
    location: "New York, NY",
    eventDate: "2023-06-15",
    postedDate: "2023-01-10",
    status: "active",
    isPremium: true,
    applicationsCount: 12,
  },
  {
    id: "j2",
    clientId: "c2",
    title: "Beach Wedding Venue in Southern California",
    category: "Venues",
    description:
      "Searching for the perfect beach venue for our August wedding. Need capacity for 150 guests with indoor backup option in case of bad weather.",
    budget: "$10,000 - $15,000",
    location: "Los Angeles, CA",
    eventDate: "2023-08-22",
    postedDate: "2023-02-05",
    status: "active",
    isPremium: true,
    applicationsCount: 8,
  },
  {
    id: "j3",
    clientId: "c3",
    title: "Fall-Themed Wedding Florist in Chicago",
    category: "Florists",
    description:
      "Need a florist who specializes in fall-themed arrangements for our October wedding. Looking for rich, warm colors and seasonal flowers.",
    budget: "$3,000 - $5,000",
    location: "Chicago, IL",
    eventDate: "2023-10-08",
    postedDate: "2023-03-15",
    status: "active",
    isPremium: false,
    applicationsCount: 5,
  },
  {
    id: "j4",
    clientId: "c4",
    title: "Winter Wedding DJ in Denver",
    category: "Music",
    description:
      "Seeking an experienced DJ for our winter wedding. Must have a diverse playlist and ability to read the crowd. Lighting package a plus.",
    budget: "$1,000 - $1,500",
    location: "Denver, CO",
    eventDate: "2023-12-30",
    postedDate: "2023-04-20",
    status: "active",
    isPremium: false,
    applicationsCount: 7,
  },
  {
    id: "j5",
    clientId: "c5",
    title: "Valentine's Day Wedding Cake Designer",
    category: "Cakes",
    description:
      "Looking for a cake designer to create a romantic Valentine's Day themed wedding cake. Three tiers with red velvet and chocolate flavors.",
    budget: "$500 - $800",
    location: "Seattle, WA",
    eventDate: "2024-02-14",
    postedDate: "2023-05-01",
    status: "active",
    isPremium: true,
    applicationsCount: 3,
  },
  {
    id: "j6",
    clientId: "c1",
    title: "Catering for NYC Wedding Reception",
    category: "Catering",
    description:
      "Need a caterer for our wedding reception. Looking for a mix of American and Italian cuisine. Must be able to accommodate dietary restrictions.",
    budget: "$8,000 - $12,000",
    location: "New York, NY",
    eventDate: "2023-06-15",
    postedDate: "2023-01-15",
    status: "active",
    isPremium: true,
    applicationsCount: 10,
  },
];

// Dummy Applications
export const dummyApplications = [
  {
    id: "a1",
    jobId: "j1",
    vendorId: "v1",
    coverLetter:
      "I would love to photograph your wedding! With over 10 years of experience in NYC weddings, I can capture your special day beautifully.",
    price: "$2,800",
    status: "pending",
    appliedDate: "2023-01-12",
    hasUnreadMessages: true,
  },
  {
    id: "a2",
    jobId: "j2",
    vendorId: "v2",
    coverLetter:
      "Our beachfront venue would be perfect for your August wedding. We can accommodate 200 guests and have an indoor option available.",
    price: "$12,500",
    status: "pending",
    appliedDate: "2023-02-07",
    hasUnreadMessages: false,
  },
  {
    id: "a3",
    jobId: "j3",
    vendorId: "v3",
    coverLetter:
      "I specialize in fall-themed floral arrangements and would love to bring your vision to life. My designs feature rich autumn colors and textures.",
    price: "$4,200",
    status: "accepted",
    appliedDate: "2023-03-18",
    hasUnreadMessages: true,
  },
  {
    id: "a4",
    jobId: "j4",
    vendorId: "v4",
    coverLetter:
      "As an experienced wedding DJ, I can create the perfect atmosphere for your winter wedding. My package includes lighting and MC services.",
    price: "$1,350",
    status: "pending",
    appliedDate: "2023-04-22",
    hasUnreadMessages: false,
  },
  {
    id: "a5",
    jobId: "j5",
    vendorId: "v5",
    coverLetter:
      "I would love to create a romantic Valentine's Day wedding cake for your special day. I specialize in elegant designs with delicious flavors.",
    price: "$650",
    status: "pending",
    appliedDate: "2023-05-03",
    hasUnreadMessages: false,
  },
];
