name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      
      - name: Deploy to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: 67.207.84.179
          username: root
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          source: "dist/"
          target: "/var/www/thevendorsconnect.com"
          strip_components: 1